apiVersion: apps/v1
kind: Deployment
metadata:
  name: layout-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layout-management
  template:
    metadata:
      labels:
        app: layout-management
    spec:
      containers:
      - name: layout-management
        image: backend-layout-management:latest
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: layout-management
spec:
  selector:
    app: layout-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
