apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: backend-order-management:latest
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: order-management
spec:
  selector:
    app: order-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060
